### ISSUE TITLE
Provide sample data for local development

### ISSUE THREAD

**Issue by kmpzr** [TheWudu/mongo_cpp#1]
Hey @TheWudu, thanks for creating this playground :)

I would love to chip in and play with C++ as well (I'm quite rust by now). Could you please provide a set of sample data to play around? Maybe in `samples` directory?

Thank you!

**Comment by TheWudu** [comment]
Hello! I added some sample files (real live from my export) to the data/Sport-sessions folder. The are spread over three years, so you can do something with the grouping / year filters already. The data itself is pretty easy so just copy / adapt whatever you need. 

If you have a good ideas what to aggregate / what statistics to show, or which fields of the sessions to also import the db, just contact me again.

If you are using runtastic (adidas running/training apps) you can just download your export with logging in to www.runtastic.com and then in settings you will find the gdpr-export trigger button. 

Best regards,
TheWudu
